global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'OpenTelemetry-example-App1'
    static_configs:
      - targets: ['docker.for.mac.host.internal:7223']

  - job_name: 'OpenTelemetry-example-App2'
    static_configs:
      - targets: ['docker.for.mac.host.internal:5000']
  - job_name: 'OpenTelemetry-example-App3'
    static_configs:
      - targets: [ 'docker.for.mac.host.internal:7265' ]
  - job_name: 'OpenTelemetry-example-App4'
    static_configs:
      - targets: [ 'docker.for.mac.host.internal:3500' ]
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'docker.for.mac.host.internal:9093' ]

# include alert rules (to be used by AlertManager)
rule_files:
  - "/etc/prometheus/alertingrule.yaml"
    

